sudo: required
cache:
  - apt
dist: xenial
language: python
matrix:
  include:
  - name: "Native Env Xenial python 3.6"
    dist: xenial
    python: "3.6"
    env:
      - INSTALL_MUJOCO=false
# command to install dependencies

before_install:
  - sudo apt update && sudo apt install libopenmpi-dev

script:
  - pip install -r requirements.txt
  - pip install -e .